/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:baf26f2d-8855-4def-9416-9c98be7e62e2",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_dbFaqW6eN",
    "aws_user_pools_web_client_id": "53qknmptu461oe8n0jtd3did8e",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://h5vl356n55ak5g757nl3bzg6d4.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-ggcbd5agefejridxyoxpejefli",
    "aws_cloud_logic_custom": [
        {
            "name": "public",
            "endpoint": "https://bd7p7atax7.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        },
        {
            "name": "chessplayers",
            "endpoint": "https://4mgsigrqo6.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        },
        {
            "name": "chesscom",
            "endpoint": "https://pq08pdiggj.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        },
        {
            "name": "lichess",
            "endpoint": "https://yj5ij5ocz9.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        },
        {
            "name": "travel",
            "endpoint": "https://qxbqiiv6nc.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        }
    ],
    "aws_user_files_s3_bucket": "pgn-bucket45655-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
